version: '2.1'
services:
  temp_logger:
    build: .
    container_name: temp_logger
    restart: always
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/mem:/dev/mem"
    privileged: true
    healthcheck:
      test: ["CMD", "python", "--version"]
      interval: 10s
      timeout: 10s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
