version: '2.1'
services:
  temp_logger:
    image: dht22-docker
    container_name: temp_logger
    restart: always
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/mem:/dev/mem"
    privileged: true
    healthcheck:
      test: ["CMD", "python", "--version"]
      interval: 10s
      timeout: 10s
      retries: 10
